### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by goney3** [kjayawar/PROFOIL-UI#1]
Hello, I noticed the Directory Structure image is 404-not found. Without being able to see the image I am not sure how the directory structure should be? Please advise. Thank you.

**Comment by kjayawar** [comment]
Hi Keith,

Apologies for the inconvenience. I think this is due to a typo in the
readme file. Please try viewing manual.html or use below link for now.

https://github.com/kjayawar/PROFOIL-UI/tree/8bb369fa8d970ce47cab2b1b71e01968997f4823

I'll fix it little later as I don't have a computer with me now

Cheers
Kanishka

**Comment by kjayawar** [comment]
Hi Keith,

I was on a vacation- so took me a while to get my hands on a computer.
Both Readme.md and manual.html have now been fixed. 

Cheers
Kanishka
